version: 0.0
os: linux
files:
  - source: app.js 
    destination: /home/ubuntu/backend
  - source: package.json
    destination: /home/ubuntu/backend
hooks:
  BeforeInstall:
    - location: deploy_scripts/beforeInstall.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy_scripts/afterInstall.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deploy_scripts/appStart.sh
      timeout: 300
      runas: ubuntu

